import type { NextPage } from 'next'
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'
import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import Link from 'next/link'
import DataJson from '../dataJson/test.json'

let Post: NextPage = ({ data }: any) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>blog{data.id}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href={"/"}> RETOUR</Link>
            <div className="">
                <h1>ID : {data.id}</h1>
                <p>{data.body}</p>
            </div>

            {
                DataJson?.map((liste: any, index: number) => {
                    return (
                        <div key={index} > {liste.id}- {liste.title}</div>)
                })
            }
        </div>
    )
}
export default Post;

export let getServerSideProps: GetServerSideProps = async ({ params }: any) => {
    let reponse = await fetch(`https://jsonplaceholder.typicode.com/posts/${params.id}`)
    let data = await reponse.json()
    console.log("Params :", params, data);

    return {
        props: {
            data,
        },
    }
}


